name: esliph-validator

services:
  validator:
    build: .
    container_name: validator
    volumes:
      - .:/var/www
      - ./docker/php/conf.d/pcov.ini:/usr/local/etc/php/conf.d/pcov.ini
    profiles:
      - cli
      - test
      - coverage

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    profiles:
      - deps
