name: esliph-validator

services:
  validator:
    build: .
    container_name: validator
    volumes:
      - .:/var/www
    profiles:
      - cli
      - test

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    profiles:
      - deps
